DROP DATABASE IF EXISTS ukunuhi;

CREATE DATABASE ukunuhi;

USE ukunuhi;

CREATE TABLE chords_by_strings (
  id INT NOT NULL AUTO_INCREMENT,
  letter TINYTEXT NOT NULL,
  suffix TINYTEXT NOT NULL,
  strings TINYTEXT NOT NULL,
  string1 TINYINT NOT NULL,
  string2 TINYINT NOT NULL,
  string3 TINYINT NOT NULL,
  string4 TINYINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE chords_by_notes(
  id INT NOT NULL AUTO_INCREMENT,
  letter TINYTEXT NOT NULL,
  suffix TINYTEXT NOT NULL,
  notes TINYTEXT NOT NULL,
  note1 TINYTEXT NOT NULL,
  note2 TINYTEXT NOT NULL,
  note3 TINYTEXT NOT NULL,
  note4 TINYTEXT NOT NULL,
  PRIMARY KEY (id)
);